development:
  sessions:
    default:
      database: lang_trainer_development
      hosts:
        - localhost:27017
      options:

test:
  sessions:
    default:
      database: lang_trainer_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0